package compiler

import (
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/fyltr/angee/internal/config"
)

func newTestCompiler(t *testing.T) *Compiler {
	t.Helper()
	return New(t.TempDir(), "test-net")
}

func TestCompileTargetService(t *testing.T) {
	c := newTestCompiler(t)
	cfg := &config.AngeeConfig{
		Name: "minimal",
		Sources: map[string]config.SourceSpec{
			"app": {Kind: "local", Target: "."},
		},
		PortLeases: map[string]config.PortLeaseSpec{
			"web": {Default: 8080},
		},
		Services: map[string]config.ServiceSpec{
			"web": {
				Runtime:   "docker",
				Source:    "app",
				Image:     "nginx",
				Lifecycle: config.LifecyclePlatform,
				Command:   []string{"nginx", "-g", "daemon off;"},
				Env:       map[string]string{"TOKEN": "${secret:api-token}"},
				Ports:     []config.ServicePort{{Host: "8080", Target: "80"}},
			},
		},
	}

	cf, err := c.Compile(cfg)
	if err != nil {
		t.Fatalf("Compile() error: %v", err)
	}
	web := cf.Services["web"]
	if web.Image != "nginx" {
		t.Errorf("web.Image = %q", web.Image)
	}
	if got, ok := web.Command.([]string); !ok || len(got) != 3 || got[0] != "nginx" {
		t.Errorf("web.Command = %#v", web.Command)
	}
	if len(web.Ports) != 1 || web.Ports[0] != "8080:80" {
		t.Errorf("web.Ports = %v", web.Ports)
	}
	if len(web.Environment) != 1 || web.Environment[0] != "TOKEN=${API_TOKEN}" {
		t.Errorf("web.Environment = %v", web.Environment)
	}
}

func TestCompilePlatformTraefikLabels(t *testing.T) {
	c := newTestCompiler(t)
	cfg := &config.AngeeConfig{
		Name: "traefik-test",
		Services: map[string]config.ServiceSpec{
			"web": {
				Image:     "nginx",
				Lifecycle: config.LifecyclePlatform,
				Domains:   []config.DomainSpec{{Host: "example.com", Port: 80, TLS: true}},
			},
		},
	}

	cf, err := c.Compile(cfg)
	if err != nil {
		t.Fatalf("Compile() error: %v", err)
	}
	web := cf.Services["web"]
	if web.Labels["traefik.enable"] != "true" {
		t.Error("expected traefik.enable=true")
	}
	if !strings.Contains(web.Labels["traefik.http.routers.web.rule"], "Host(`example.com`)") {
		t.Error("expected Host rule for example.com")
	}
	if web.Labels["traefik.http.routers.web.entrypoints"] != "websecure" {
		t.Error("expected websecure entrypoint for TLS")
	}
}

func TestCompileVolumes(t *testing.T) {
	c := newTestCompiler(t)
	cfg := &config.AngeeConfig{
		Name: "volume-test",
		Volumes: map[string]config.VolumeSpec{
			"pgdata": {Driver: "local-fs", Path: ".angee/data/postgres"},
		},
		Services: map[string]config.ServiceSpec{
			"db": {
				Image:   "postgres",
				Volumes: []config.ServiceVolume{{Name: "pgdata", Target: "/var/lib/postgresql/data"}},
			},
		},
	}
	cf, err := c.Compile(cfg)
	if err != nil {
		t.Fatalf("Compile() error: %v", err)
	}
	if _, ok := cf.Volumes["pgdata"]; !ok {
		t.Fatal("expected pgdata volume")
	}
	if got := cf.Services["db"].Volumes; len(got) != 1 || got[0] != "pgdata:/var/lib/postgresql/data" {
		t.Errorf("db volumes = %v", got)
	}
}

func TestCompileAgentItems(t *testing.T) {
	c := newTestCompiler(t)
	cfg := &config.AngeeConfig{
		Name: "agent-test",
		MCPServers: map[string]config.MCPServerSpec{
			"files": {Transport: "sse", URL: "http://files/mcp"},
		},
		Agents: &config.AgentRegistrySpec{
			Items: map[string]config.AgentSpec{
				"bot": {
					Image:        "agent:latest",
					Lifecycle:    config.LifecycleSystem,
					Role:         "operator",
					MCPServers:   []string{"files"},
					SystemPrompt: "You are useful.",
				},
			},
		},
	}

	cf, err := c.Compile(cfg)
	if err != nil {
		t.Fatalf("Compile() error: %v", err)
	}
	svc := cf.Services["agent-bot"]
	if svc.Image != "agent:latest" {
		t.Errorf("agent image = %q", svc.Image)
	}
	if svc.Restart != "always" {
		t.Errorf("agent restart = %q", svc.Restart)
	}
	foundMCP := false
	for _, env := range svc.Environment {
		if env == "ANGEE_MCP_FILES_URL=http://files/mcp" {
			foundMCP = true
		}
	}
	if !foundMCP {
		t.Errorf("agent env = %v", svc.Environment)
	}
}

func TestWriteComposeFile(t *testing.T) {
	dir := t.TempDir()
	path := filepath.Join(dir, "docker-compose.yaml")
	cf := &ComposeFile{Name: "test", Services: map[string]ComposeService{"web": {Image: "nginx"}}}
	if err := Write(cf, path); err != nil {
		t.Fatalf("Write() error: %v", err)
	}
	data, err := os.ReadFile(path)
	if err != nil {
		t.Fatal(err)
	}
	if !strings.Contains(string(data), "Generated by angee-operator") {
		t.Error("expected generated header")
	}
	if !strings.Contains(string(data), "image: nginx") {
		t.Error("expected service YAML")
	}
}
