name: official/angee-default
description: |
  Angee platform — operator + OpenBao + admin agent.
  The foundation for any Angee stack. Add components with:
    angee add postgres
    angee add redis
    angee add angee-django
version: "1.0"
author: angee

parameters:
  - name: ProjectName
    description: "Project name (lowercase, hyphens)"
    required: true
    validate: "^[a-z][a-z0-9-]+$"

  - name: Domain
    description: "Primary domain (e.g. myapp.io or localhost)"
    default: "localhost"

# Only one secret: the Anthropic API key for agents
secrets:
  - name: anthropic-api-key
    description: "Anthropic API key for AI agents (get yours at console.anthropic.com)"
    required: true
