// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type KeyValue struct {
	Key   string `json:"key"`
	Value string `json:"value"`
}

type KeyValueInput struct {
	Key   string `json:"key"`
	Value string `json:"value"`
}

type Mutation struct {
}

type MutationResult struct {
	Status  string  `json:"status"`
	Name    *string `json:"name,omitempty"`
	Message *string `json:"message,omitempty"`
}

type Query struct {
}

type ServiceInput struct {
	Name    *string          `json:"name,omitempty"`
	Runtime *string          `json:"runtime,omitempty"`
	Image   *string          `json:"image,omitempty"`
	Command []string         `json:"command,omitempty"`
	Mounts  []string         `json:"mounts,omitempty"`
	Env     []*KeyValueInput `json:"env,omitempty"`
	Ports   []string         `json:"ports,omitempty"`
	Workdir *string          `json:"workdir,omitempty"`
	Start   *bool            `json:"start,omitempty"`
}

type StackInitInput struct {
	Template string           `json:"template"`
	Path     *string          `json:"path,omitempty"`
	Inputs   []*KeyValueInput `json:"inputs,omitempty"`
	Force    *bool            `json:"force,omitempty"`
}

type StackInitResult struct {
	Status   string `json:"status"`
	Template string `json:"template"`
	Root     string `json:"root"`
}

type StackRuntimeInput struct {
	Services []string `json:"services,omitempty"`
	Build    *bool    `json:"build,omitempty"`
}

type WorkspaceCreateInput struct {
	Template string           `json:"template"`
	Name     *string          `json:"name,omitempty"`
	Inputs   []*KeyValueInput `json:"inputs,omitempty"`
	TTL      *string          `json:"ttl,omitempty"`
	Start    *bool            `json:"start,omitempty"`
}

type WorkspaceUpdateInput struct {
	Inputs []*KeyValueInput `json:"inputs,omitempty"`
	TTL    *string          `json:"ttl,omitempty"`
}
