schema: ../internal/operator/schema.graphql
extensions:
  graphql-markdown:
    rootPath: ./
    baseURL: reference/graphql
    linkRoot: /
    homepage: ./scripts/graphql-homepage.md
    pretty: false
    printer: "@graphql-markdown/printer-legacy"
    loaders:
      GraphQLFileLoader: "@graphql-tools/graphql-file-loader"
